# Prueba de chi-cuadrado de independencia

Este cuaderno realiza una prueba de chi-cuadrado sobre una tabla de contingencia generada aleatoriamente. La prueba de chi-cuadrado permite evaluar si existe dependencia entre dos variables categóricas.


In [3]:

import numpy as np
from scipy.stats import chi2_contingency

# Crear tabla de contingencia (2x3) con datos de conteo
table = np.array([[20, 15, 30],
                  [25, 30, 20]])

# Mostrar la tabla de contingencia
print("""Tabla de contingencia:
""", table)

# Realizar la prueba de chi-cuadrado
chi2, p, dof, expected = chi2_contingency(table)

print(f"Estadístico chi-cuadrado: {chi2:.4f}")
print(f"Grados de libertad: {dof}")
print(f"""Valores esperados:
      {expected}""")
print(f"p-valor: {p:.4f}")

if p < 0.05:
    print("Se rechaza la hipótesis nula. Existe evidencia de dependencia entre las variables.")
else:
    print("No se puede rechazar la hipótesis nula. No hay evidencia suficiente de dependencia.")


Tabla de contingencia:
 [[20 15 30]
 [25 30 20]]
Estadístico chi-cuadrado: 6.8764
Grados de libertad: 2
Valores esperados:
      [[20.89285714 20.89285714 23.21428571]
 [24.10714286 24.10714286 26.78571429]]
p-valor: 0.0321
Se rechaza la hipótesis nula. Existe evidencia de dependencia entre las variables.
